### ISSUE TITLE
List deserialization issue

### ISSUE THREAD

**Issue by abedeoan** [graphql-java-generator/graphql-maven-plugin-project#3]
Hello, 

I am building a very simple client, following the code samples provided with the plugin. 
Schema sample below: 

schema {
    query: QueryType
}
type QueryType {
    getAllEquipments(): [MyEquipment!]!
}
interface Equipment {
    customerName: String
    id: ID!
}
type MyEquipment implements Equipment {
    customerName: String
    id: ID!
} 

The simple query looks like this: 
    public List< MyEquipment > getAllEquipments() throws GraphQLExecutionException, GraphQLRequestPreparationException {
        return queryType.getAllEquipments(/* "{customerName id}" */ "");
    }

However I get a deserialization issue related to the list (from what I understand) - stacktrace below: 

23:48:54.573 [main] TRACE com.graphql_java_generator.client.QueryExecutorImpl - Generated GraphQL request: {"query":"query {getAllEquipments{ customerName id}}","variables":null,"operationName":null}
com.graphql_java_generator.client.response.GraphQLExecutionException: Error when executing query <{"query":"query {MyEquipment{ customerName id}}","variables":null,"operationName":null}>: Cannot deserialize instance of `com.QueryTypeMyEquipment` out of START_ARRAY token
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.graphql_java_generator.client.QueryExecutorImpl.execute(QueryExecutorImpl.java:94)
	at com.QueryType.getAllEquipments(QueryType.java:132)
	...
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.QueryTypeMyEquipment` out of START_ARRAY token
 at [Source: UNKNOWN; line: -1, column: -1]

Note that I am using the classes for the entities and queries as generated by the plugin version 1.0.0-RC2, I am not changing any class annotation related to serialization.

Any advice would be appreciated. 

Amelia

**Comment by abedeoan** [comment]
Later edit: the issue was on our side (the way the JSON response was structured); nothing related to the actual code generation from the plugin. Hence closing this ticket.
